Workbook:
    {name  : "Cars", checks : [WC]}
Sheets:
  [ {name : Cars,
    checks : [SC1,SC2],
    Rows :
    [{from : 2, to : 10, checks : [RC1, RC3, RC4]},
     {from : 3, to: 3, checks : [RC2]}],
    Columns:
    [{from : 4, to : 4, checks : [CC1, CC2]}, {from : 12, to : 34, checks : [CC1, CC2]}],
    Cells:
    [{cell: "(3,4)", checks : [CC4]}, {cell: "(32,4)", checks : [CC4]}] },
    {name : Carettes,
    checks : [SC1,SC2],
    Rows :
    [{from : 2, to : 10, checks : [RC1, RC3, RC4]},
     {from : 3, to: 3, checks : [RC2]}],
    Columns:
    [{from : 4, to : 4, checks : [CC1, CC2]}],
    Cells:
    [{cell: "(3,4)", checks : [CC4]}] }]